name: Deploy Sky Take-Out Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'foodDelivery/sky-server/**'
      - 'foodDelivery/sky-pojo/**'
      - 'foodDelivery/sky-common/**'
      - 'foodDelivery/pom.xml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package -f foodDelivery/pom.xml -DskipTests

      # --- 这是我们新增的“侦察”步骤 ---
      - name: Verify build artifacts
        run: ls -l foodDelivery/sky-server/target/
      # ------------------------------------

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p /project/sky-take-out/jar
            PID=$(ps -ef | grep 'sky-server.jar' | grep -v grep | awk '{print $2}')
            if [ -n "$PID" ]; then
              kill -9 $PID
            fi
            rm -f /project/sky-take-out/jar/sky-server.jar
            mv ${{ github.workspace }}/foodDelivery/sky-server/target/*.jar /project/sky-take-out/jar/sky-server.jar
            nohup java -jar /project/sky-take-out/jar/sky-server.jar --spring.profiles.active=prod &