# name: Deploy Sky Take-Out Backend

# on:
#   push:
#     branches: [ "main" ]
#     paths:
#       - 'foodDelivery/**'

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up JDK 17
#         uses: actions/setup-java@v3
#         with:
#           java-version: '17'
#           distribution: 'temurin'
#           cache: maven

#       - name: Build with Maven
#         run: mvn -B package -f foodDelivery/pom.xml -DskipTests

#       # 修正第一步：将构建好的 JAR 文件复制并重命名到工作区根目录
#       # 这样可以简化 scp 的源路径，避免在服务器上创建多余的目录
#       - name: Prepare Artifact for Deployment
#         run: cp foodDelivery/sky-server/target/*.jar ./sky-server.jar

#       # 修正第二步：更新 scp-action 的 source 路径
#       - name: Copy JAR to Server
#         # 建议：为了工作流的稳定性，最好将 @master 替换为具体的版本号，例如 @v0.1.7
#         uses: appleboy/scp-action@master
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USERNAME }}
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           # 源文件现在是工作区的根目录下的 sky-server.jar
#           source: "sky-server.jar"
#           # 目标路径保持不变
#           target: "/project/sky-take-out/jar"
#           # 由于上一步已经复制并重命名，这里的 rename 参数可以省略
#           # 但为了清晰起见，保留也可以
#           rename: "sky-server.jar"
#           # 增加 overwrite 选项确保每次都覆盖旧文件
#           overwrite: true

#       # 远程部署脚本无需改动
#       - name: Restart Service on Server
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USERNAME }}
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           script: |
#             # 脚本现在可以正确地在 /project/sky-take-out/jar/sky-server.jar 路径找到文件
#             PID=$(ps -ef | grep 'sky-server.jar' | grep -v grep | awk '{print $2}')
#             if [ -n "$PID" ]; then
#               kill -9 $PID
#             fi
            
#             # 以后台不挂断的方式启动新版本的 Java 程序
#             nohup /www/server/java/jdk-21.0.2/bin/java  -jar /project/sky-take-out/jar/sky-server.jar --spring.profiles.active=prod > /dev/null 2>&1 &

name: Deploy Sky Take-out Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'foodDelivery/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 步骤 1: 正常使用 Maven 打包
      - name: Build with Maven
        run: mvn -B package -f foodDelivery/pom.xml -DskipTests

      # 步骤 2: 将构建好的 JAR 文件复制到服务器
      - name: Copy JAR to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "foodDelivery/sky-server/target/*.jar"
          target: "/project/sky-take-out/jar"
          rename: "sky-server.jar"
          overwrite: true

      # 步骤 3: 在服务器上根据 Secret 创建或覆盖【两个】配置文件
      - name: Create Configuration Files on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 从 Secret 创建基础配置文件 application.yml
            echo "${{ secrets.APPLICATION_YML }}" > /project/sky-take-out/jar/application.yml
            
            # 从 Secret 创建生产环境配置文件 application-prod.yml
            echo "${{ secrets.APPLICATION_PROD_YML }}" > /project/sky-take-out/jar/application-prod.yml

      # 步骤 4: 远程重启服务
      - name: Restart Service on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 停止旧服务
            PID=$(ps -ef | grep 'sky-server.jar' | grep -v grep | awk '{print $2}')
            if [ -n "$PID" ]; then
              kill -9 $PID
            fi

            # 加载环境变量
            source /etc/profile

            # 切换到 JAR 包所在目录再执行启动命令
            cd /project/sky-take-out/jar
            # 启动时，Spring Boot 会先加载 application.yml，再加载 application-prod.yml 进行覆盖
            nohup java -jar sky-server.jar --spring.profiles.active=prod > /dev/null 2>&1 &

