name: Deploy Sky Take-Out Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'sky-server/**'
      - 'sky-pojo/**'
      - 'sky-common/**'
      - 'pom.xml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Java 环境
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. 使用 Maven 打包 (修正部分)
      - name: Build with Maven
        # 修正：去掉了 --file pom.xml 参数，让 Maven 自动查找
        run: mvn -B package -DskipTests

      # 4. 部署到服务器
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p /project/sky-take-out/jar
            PID=$(ps -ef | grep 'sky-server.jar' | grep -v grep | awk '{print $2}')
            if [ -n "$PID" ]; then
              kill -9 $PID
            fi
            rm -f /project/sky-take-out/jar/sky-server.jar
            mv ${{ github.workspace }}/sky-server/target/*.jar /project/sky-take-out/jar/sky-server.jar
            nohup java -jar /project/sky-take-out/jar/sky-server.jar --spring.profiles.active=prod &