name: Deploy Sky Take-Out Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'foodDelivery/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package -f foodDelivery/pom.xml -DskipTests

      # 关键修正第一步：使用 scp-action 将构建好的 jar 文件复制到服务器
      - name: Copy JAR to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          # 源文件：Runner 虚拟机上的 jar 文件路径
          source: "foodDelivery/sky-server/target/*.jar"
          # 目标路径：您云服务器上的目录
          target: "/project/sky-take-out/jar"
          # 将文件重命名为 sky-server.jar
          rename: "sky-server.jar"

      # 关键修正第二步：使用 ssh-action 远程执行命令
      - name: Restart Service on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # 现在文件已经在服务器上了，我们只需要在这里停止和启动服务
            PID=$(ps -ef | grep 'sky-server.jar' | grep -v grep | awk '{print $2}')
            if [ -n "$PID" ]; then
              kill -9 $PID
            fi
            
        
            # 以后台不挂断的方式启动新版本的 Java 程序
            # 修正：使用了 java 的绝对路径
            nohup /www/server/java/jdk-21.0.2/bin/java -jar /project/sky-take-out/jar/sky-server.jar --spring.profiles.active=prod &